name: react_widgets
description: A port of react-widgets for Dart.
version: 0.0.1
author: Jonas Kello <jonas.kello@gmail.comm>
#homepage: https://www.example.com
environment:
  sdk: '>=1.0.0 <2.0.0'
dependencies:
  react: "^0.7.1"
dev_dependencies:
  test: '>=0.12.0 <0.13.0'
  intl: "^0.12.4"
